name: CSS Stylelint

on:
  workflow_call:

jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Stylelint
        run: |
          npm install --global stylelint stylelint-config-standard

      - name: Run Stylelint
        run: |
          stylelint "**/*.css" || true
